config/routes.rb
Rails.application.routes.draw do  
  resources :quiz_attempts
  resources :quizzes do 
    member do 
      get 'attempt'
      get 'assign'
      post 'assignment'
    end
  end
  resources :groups
  resources :products  do 
    collection do 
      get 'get_codes'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    patch 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
  resources :users
  root 'users#index'
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy, :assign, :assignment]

  # GET /quizzes
  # GET /quizzes.json
  def index
    if current_user.admin?
      @quizzes = Quiz.all
    else
      @quizzes = Quiz.where(product_id: current_user.products.map(&:id)).all
    end
    
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def assign

  end

  def assignment
    puts params.inspect    
    users = []
    users = users + Group.find(params[:group]).users unless params[:group].blank?    
    users = users + User.find(params[:users]) unless params[:users].blank?
    puts users.inspect
    users.each do |user|
      q = QuizAttempt.where(user_id: user.id, status_cd: 0, quiz_id: @quiz.id).first_or_create            
      q.total_questions = @quiz.answers.count      
      q.save!
    end
    redirect_to @quiz, notice: 'Quiz was successfully assigned.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:user_id, :product_id, :group_id, :title, answers_attributes: [:id, :question, :option_1, :option_2, :option_3, :option_4, :correct_answer, :_destroy])
    end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_answer_fields.html.slim
.nested-fields
  .row
    .col
      = f.input :question
  .row
    .col
      = f.input :option_1    
    .col
      = f.input :option_2
  .row
    .col
      = f.input :option_3
    .col
      = f.input :option_4
  .row
    .col
      = f.input :correct_answer, as: :radio_buttons, collection: [['1', 'Option 1'], ['2', 'Option 2'], ['3', 'Option 3'], ['4', 'Option 4']], label_method: :second, value_method: :first    
    .col.text-right
      = link_to_remove_association "Remove answer", f, class: 'btn btn-danger btn-sm'

  br

app/views/quizzes/_form.html.slim
= simple_form_for(@quiz) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
  .row
    .col
      = f.input :title
    .col
      = f.association :product
  /.row
    .col
      = f.association :group
      /= f.association :user
    .col
  .row
    .col
      h3 Questions
      #ansers
        = f.simple_fields_for :answers do |answer|
          = render 'answer_fields', f: answer
  .links.text-right
    = link_to_add_association 'Add Question', f, :answers, class: 'btn btn-primary btn-flat'   
    
    
  br
  .form-actions
    == render 'layouts/partials/form_action_buttons', options: { form: f, index_path: quizzes_path}

app/views/quizzes/assign.html.slim
= simple_form_for(@quiz, :url => assignment_quiz_path, :method => :post) do |f|
  .row
    .col
      h1 = @quiz.title
  .row
    .col
      strong
        | Created By
    .col
      = @quiz.user.name
    .col
      strong
        | Product
    .col
      = @quiz.product.name
  .row
    .col
      br
  .row
    .col
      = label_tag "Group" 
      = select_tag "group", options_from_collection_for_select(Group.all, 'id', 'name', ''), class: 'form-control', include_blank: true    
    .col
      = label_tag "Users" 
      = select_tag "users[]", options_from_collection_for_select(User.all, 'id', 'name', ''), class: 'form-control', multiple: true
  .row
    .col
      br
  .row
    .col.text-right
      = f.button :submit, "Assign Quiz", class: 'btn btn-success btn-flat'

  /.row
    .col
      h3
        | Questions
  /- @quiz.answers.each do |answer|
    .card    
      .card-body
        .card-title
          = answer.question
        .card-text
          ul
            li class="#{answer.correct_answer == 1 ? 'text-success' : ''}" 
              = answer.option_1
            li class="#{answer.correct_answer == 2 ? 'text-success' : ''}" 
              = answer.option_2
            li class="#{answer.correct_answer == 3 ? 'text-success' : ''}" 
              = answer.option_3
            li class="#{answer.correct_answer == 4 ? 'text-success' : ''}" 
              = answer.option_4
            
  br
  /= render 'layouts/partials/actions_buttons', back_path: quizzes_path, edit_path: edit_quiz_path(@quiz)

app/views/quizzes/edit.html.slim
h1 Editing quiz

== render 'form'

/ => link_to 'Show', @quiz
/ '|
/ =< link_to 'Back', quizzes_path

app/views/quizzes/index.html.slim
h1 Listing Quizzes

table class="table table-striped datatable"
  thead
    tr
      th Title
      th Created by
      th Product
      /th Group
      th Actions

  tbody
    - @quizzes.each do |quiz|
      tr
        td = quiz.title
        td = quiz.user.name
        td = quiz.product.name
        /td = quiz.group.name
        td 
          = link_to 'Assign Quiz', assign_quiz_path(quiz)
          |  |  
          = link_to 'Show', quiz
          |  |  
          = link_to 'Edit', edit_quiz_path(quiz)
          /= link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br
.text-center
  = link_to 'New Quiz', new_quiz_path, class: "btn btn-primary"

app/views/quizzes/new.html.slim
h1 New quiz

== render 'form'

/= link_to 'Back', quizzes_path

app/views/quizzes/show.html.slim
.row
  .col
    h1 = @quiz.title
.row
  .col
    strong
      | Created By
  .col
    = @quiz.user.name
  .col
    strong
      | Product
  .col
    = @quiz.product.name
.row
  .col
    br
    
/.row
  .col
    strong
      | Group
  .col
    = @quiz.group.name
  .col
    strong
      
  .col
.row
  .col
    br

.row
  .col
    h3
      | Questions
- @quiz.answers.each do |answer|
  .card    
    .card-body
      .card-title
        = answer.question
      .card-text
        ul
          li class="#{answer.correct_answer == 1 ? 'text-success' : ''}" 
            = answer.option_1
          li class="#{answer.correct_answer == 2 ? 'text-success' : ''}" 
            = answer.option_2
          li class="#{answer.correct_answer == 3 ? 'text-success' : ''}" 
            = answer.option_3
          li class="#{answer.correct_answer == 4 ? 'text-success' : ''}" 
            = answer.option_4
          
br
= render 'layouts/partials/actions_buttons', back_path: quizzes_path, edit_path: edit_quiz_path(@quiz)