config/routes.rb
Rails.application.routes.draw do  
  resources :quiz_attempts
  resources :quizzes do 
    member do 
      get 'attempt'
      get 'assign'
      post 'assignment'
    end
  end
  resources :groups
  resources :products  do 
    collection do 
      get 'get_codes'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    patch 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
  resources :users
  root 'users#index'
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  has_and_belongs_to_many :users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    redirect_to groups_path
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.slim
= simple_form_for(@group) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .row
    .col
      = f.input :name
    .col
  == render 'layouts/partials/form_action_buttons', options: { form: f, index_path: groups_path}
  

app/views/groups/edit.html.slim
h1 Editing group

== render 'form'

app/views/groups/index.html.slim
h1 Groups

table class="table table-striped datatable"
  thead
    tr
      th Name    
      th Actions

  tbody
    - @groups.each do |group|
      tr
        td = group.name
        /td = link_to 'Show', group
        td = link_to 'Edit', edit_group_path(group)
        /td = link_to 'Destroy', group, data: { confirm: 'Are you sure?' }, method: :delete

br
.text-center
  = link_to 'New Group', new_group_path, class: "btn btn-primary"

app/views/groups/new.html.slim
h1 New group

== render 'form'

/= link_to 'Back', groups_path

app/views/groups/show.html.slim
p#notice = notice

p
  strong Name:
  = @group.name

=> link_to 'Edit', edit_group_path(@group)
'|
=< link_to 'Back', groups_path