config/routes.rb
Rails.application.routes.draw do  
  resources :quiz_attempts
  resources :quizzes do 
    member do 
      get 'attempt'
      get 'assign'
      post 'assignment'
    end
  end
  resources :groups
  resources :products  do 
    collection do 
      get 'get_codes'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    patch 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
  resources :users
  root 'users#index'
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  has_and_belongs_to_many :users
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    redirect_to products_path
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_products
    search_string = params[:q]
    products = Product.where(name: /.*#{search_string}.*/i)
    respond_to do |format|
      format.json { render json: { items: products.map { |product| { id: product.id.to_s, code: product.name } }, total_count: products.length, incomplete_results: false } }
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.slim
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/products/edit.html.slim
h1 Editing product

== render 'form'

/ => link_to 'Show', @product
/ '|
/ =< link_to 'Back', products_path

app/views/products/index.html.slim
h1 Products

table class="table table-striped datatable"
  thead
    tr
      th Name    
      th Actions

  tbody
    - @products.each do |product|
      tr
        td = product.name
        /td = link_to 'Show', product
        td = link_to 'Edit', edit_product_path(product)
        /td = link_to 'Destroy', product, data: { confirm: 'Are you sure?' }, method: :delete

br
.text-center
  = link_to 'New Product', new_product_path, class: "btn btn-primary"

app/views/products/new.html.slim
h1 New product

== render 'form'

/= link_to 'Back', products_path

app/views/products/show.html.slim
p#notice = notice

p
  strong Name:
  = @product.name

=> link_to 'Edit', edit_product_path(@product)
'|
=< link_to 'Back', products_path