config/routes.rb
Rails.application.routes.draw do  
  resources :quiz_attempts
  resources :quizzes do 
    member do 
      get 'attempt'
      get 'assign'
      post 'assignment'
    end
  end
  resources :groups
  resources :products  do 
    collection do 
      get 'get_codes'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    patch 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end
  resources :users
  root 'users#index'
end

app/views/layouts/partials/_actions_buttons.html.slim
.row
  .col
    - if defined? back_path
      = link_to back_path, class: 'btn btn-primary btn-flat' do
        i.fa.fa-angle-double-left
        | &nbsp; Back
  .col.text-right
    - if defined? edit_path
      = link_to edit_path, class: 'btn btn-info btn-flat'
        i.fa.fa-pencil
        | &nbsp; Edit

app/views/layouts/partials/_form_action_buttons.html.slim
.row
  .col
    = link_to options[:index_path], class: 'btn btn-primary btn-flat' do
      i.fa.fa-angle-double-left
      | &nbsp; Back
  
  .col.text-right
    = options[:form].button :submit, id: 'create_update_user', class: 'btn btn-success btn-flat' do
      i.fa.fa-refresh
      - if options[:form].object.id.nil?
        | &nbsp; Create
      - else
        | &nbsp; Update
      | &nbsp;
      = options[:form].object.class.name.titleize.camelcase

app/views/layouts/partials/_header.html.slim
.d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.mb-3.bg-white.border-bottom.shadow-sm
  h5.my-0.mr-md-auto.font-weight-normal 
    = current_user.name
  /nav.my-2.my-md-0.mr-md-3
    a.p-2.text-dark href="#"  Features
    a.p-2.text-dark href="#"  Enterprise
    a.p-2.text-dark href="#"  Support
    a.p-2.text-dark href="#"  Pricing
  =link_to destroy_user_session_path, :method => :delete do
    i.fa.fa-sign-out
    | &nbsp;Sign out
  /a.btn.btn-outline-primary href="#"  Sign up

app/views/layouts/partials/_sidebar.html.slim
.sidebar-header
  h3 Telenor B2B Quiz Application
ul.list-unstyled.components  
  - if can? :read, User
    li class="#{params[:controller] == "users" ? 'active' : ''}"
      = link_to users_path do 
        | Users  
  - if can? :read, Product
    li class="#{params[:controller] == "products" ? 'active' : ''}"
      = link_to products_path do 
        | Products
  - if can? :read, Group        
    li class="#{params[:controller] == "groups" ? 'active' : ''}"
      = link_to groups_path do 
        | Groups
  - if can? :read, Quiz
    li class="#{params[:controller] == "quizzes" ? 'active' : ''}"
      = link_to quizzes_path do 
        | Quizzes
  - if can? :read, QuizAttempt
    li class="#{params[:controller] == "quiz_attempts" ? 'active' : ''}"
      = link_to quiz_attempts_path do 
        | Assinged Quizzes
    /a href="#"  Home 2
  /li
    a href="#"  Portfolio
  /li
    a href="#"  Contact